/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bdl;

import java.awt.HeadlessException;
import koneksi.koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AINA NUR ILLAH
 */
public class Form_Penjualan extends javax.swing.JPanel {

    protected void tabelBarang() {
        DefaultTableModel modelBrg = new DefaultTableModel();
        modelBrg.addColumn("ID BARANG");
        modelBrg.addColumn("NAMA BARANG");
        modelBrg.addColumn("JUMLAH");
        modelBrg.addColumn("HARGA");

        try {
            String sql1 = "SELECT * FROM barang ORDER BY id_barang";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql1);

            while (res.next()) {
                modelBrg.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4)});
            }
            jTableBarang.setModel(modelBrg);

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    protected void tabelJasa() {
        DefaultTableModel modelJasa = new DefaultTableModel();
        modelJasa.addColumn("ID JASA");
        modelJasa.addColumn("NAMA JASA");
        modelJasa.addColumn("HARGA");

        try {
            String sql1 = "SELECT * FROM jasa ORDER BY id_jasa";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql1);

            while (res.next()) {
                modelJasa.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3)});
            }
            jTableJasa.setModel(modelJasa);

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    protected void tabelPelanggan() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID PELANGGAN");
        model.addColumn("NAMA PELANGGAN");
        model.addColumn("NOMOR");
        model.addColumn("EMAIL");
        model.addColumn("ALAMAT");

        try {
            String sql = "SELECT * FROM pelanggan ORDER BY id_pelanggan";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
            }
            jTablePelanggan.setModel(model);

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    protected void tabelPenjualan() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID PENJUALAN");
        model.addColumn("ID PELANGGAN");
        model.addColumn("ID BARANG");
        model.addColumn("ID JASA");
        model.addColumn("JUMLAH BARANG");
        model.addColumn("TOTAL HARGA");
        model.addColumn("TANGGAL");
        try {
            String sql = "SELECT * FROM penjualan ORDER BY id_penjualan";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7)});
            }
            jTable1.setModel(model);

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    /**
     * Creates new form Form_Dbarang
     */
    public Form_Penjualan() {
        initComponents();
        tabelBarang();
        tabelJasa();
        tabelPelanggan();
        tabelPenjualan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDbarang = new javax.swing.JPanel();
        datadbarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableJasa = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableBarang = new javax.swing.JTable();
        jTextFieldIDPJ = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIDBR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldJMLBR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIDJasa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIDPel = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePelanggan = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldHargaBr = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldHargaJs = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButtonHapus = new javax.swing.JButton();
        jButtonUbah = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldCariPel = new javax.swing.JTextField();
        jTextFieldCariBarang = new javax.swing.JTextField();
        jTextFieldCariPenjualan = new javax.swing.JTextField();
        jTextFieldCariJasa = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldHarga = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        panelDbarang.setLayout(new java.awt.CardLayout());

        datadbarang.setBackground(new java.awt.Color(204, 204, 255));
        datadbarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setText("Penjualan");
        datadbarang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 19, -1, -1));

        jTableJasa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Jasa", "Nama Jasa", "Harga Jasa"
            }
        ));
        jTableJasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableJasaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableJasa);

        datadbarang.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 420, 250));

        jTableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Barang", "Nama Barang", "Jumlah Barang Supply", "Harga"
            }
        ));
        jTableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBarangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableBarang);

        datadbarang.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, 470, 250));
        datadbarang.add(jTextFieldIDPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 112, 150, -1));

        jLabel2.setText("ID Penjualan");
        datadbarang.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 85, -1, -1));

        jLabel3.setText("ID Barang");
        datadbarang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 165, -1, -1));
        datadbarang.add(jTextFieldIDBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 192, 150, -1));

        jLabel4.setText("Jumlah Barang");
        datadbarang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));
        datadbarang.add(jTextFieldJMLBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 150, -1));

        jLabel5.setText("ID Jasa");
        datadbarang.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 85, -1, -1));
        datadbarang.add(jTextFieldIDJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 112, 155, -1));

        jLabel6.setText("ID Pelanggan");
        datadbarang.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 165, -1, -1));
        datadbarang.add(jTextFieldIDPel, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 192, 155, -1));

        jTablePelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Pelanggan", "Nama Pelanggan", "Nomor Telpon", "Email", "Alamat"
            }
        ));
        jTablePelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePelangganMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTablePelanggan);

        datadbarang.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 420, 250));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Pelanggan");
        datadbarang.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Jasa");
        datadbarang.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Barang");
        datadbarang.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, -1, -1));

        jButtonTambah.setText("TAMBAH");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });
        datadbarang.add(jButtonTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 90, 100, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID PENJUALAN", "ID PELANGGAN", "ID BARANG", "ID JASA", "JUMLAH BARANG", "TOTAL HARGA", "TANGGAL"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        datadbarang.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 1330, 360));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("PENJUALAN");
        datadbarang.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, -1, -1));
        datadbarang.add(jTextFieldHargaBr, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 150, -1));

        jLabel11.setText("Cari");
        datadbarang.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 260, -1, -1));
        datadbarang.add(jTextFieldHargaJs, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 140, -1));

        jLabel12.setText("Harga Barang");
        datadbarang.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        jLabel13.setText("Harga Jasa");
        datadbarang.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, -1));
        datadbarang.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 140, -1));

        jButtonHapus.setText("HAPUS");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        datadbarang.add(jButtonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 140, 100, 50));

        jButtonUbah.setText("UBAH");
        jButtonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbahActionPerformed(evt);
            }
        });
        datadbarang.add(jButtonUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 180, 100, 50));

        jLabel14.setText("Tanggal");
        datadbarang.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, -1, -1));

        jLabel15.setText("Cari");
        datadbarang.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, -1, -1));

        jLabel16.setText("Cari");
        datadbarang.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));

        jLabel17.setText("Cari");
        datadbarang.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));
        datadbarang.add(jTextFieldCariPel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 130, -1));
        datadbarang.add(jTextFieldCariBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 260, 130, -1));
        datadbarang.add(jTextFieldCariPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 130, -1));
        datadbarang.add(jTextFieldCariJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 130, -1));

        jLabel18.setText("Harga");
        datadbarang.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));
        datadbarang.add(jTextFieldHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 140, -1));

        panelDbarang.add(datadbarang, "card2");

        add(panelDbarang, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jTableJasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableJasaMouseClicked
        // TODO add your handling code here:
        int baris = jTableJasa.rowAtPoint(evt.getPoint());

        String id = jTableJasa.getValueAt(baris, 0).toString();
        jTextFieldIDJasa.setText(id);

        String harga = jTableJasa.getValueAt(baris, 2).toString();
        jTextFieldHargaJs.setText(harga);
    }//GEN-LAST:event_jTableJasaMouseClicked

    private void jTablePelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePelangganMouseClicked
        // TODO add your handling code here:
        int baris = jTablePelanggan.rowAtPoint(evt.getPoint());

        String id = jTablePelanggan.getValueAt(baris, 0).toString();
        jTextFieldIDPel.setText(id);
    }//GEN-LAST:event_jTablePelangganMouseClicked

    private void jTableBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBarangMouseClicked
        // TODO add your handling code here:
        int baris = jTableBarang.rowAtPoint(evt.getPoint());

        String id = jTableBarang.getValueAt(baris, 0).toString();
        jTextFieldIDBR.setText(id);

        String harga = jTableBarang.getValueAt(baris, 3).toString();
        jTextFieldHargaBr.setText(harga);
    }//GEN-LAST:event_jTableBarangMouseClicked

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        // TODO add your handling code here:
        int jumlah = Integer.parseInt(jTextFieldJMLBR.getText());
        int harga = Integer.parseInt(jTextFieldHargaBr.getText());
        int hargaj = Integer.parseInt(jTextFieldHargaJs.getText());
        int total = (harga*jumlah) + hargaj;
        Date p = jDateChooser1.getDate();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalLahirStr = dateFormat.format(p);
        
        try {
//        String jml = jTextFieldJMLBR.getText();
            String sql = "INSERT INTO penjualan VALUES(?, ?, ?, ?, ?, ?, ?)";
            String sql1 = "UPDATE barang set jumlah_br_sup=jumlah_br_sup-" + jumlah + " WHERE id_barang ='" + jTextFieldIDBR.getText() + "'";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            java.sql.PreparedStatement pst = conn.prepareStatement(sql1);
            pstm.setString(1, jTextFieldIDPJ.getText());
            pstm.setString(2, jTextFieldIDPel.getText());
            pstm.setString(3, jTextFieldIDBR.getText());
            pstm.setString(4, jTextFieldIDJasa.getText());
            pstm.setInt(5, jumlah);
            pstm.setInt(6, total);
            pstm.setDate(7, java.sql.Date.valueOf(tanggalLahirStr));

            pstm.executeUpdate();
            pst.executeUpdate();
            tabelPenjualan();
            tabelBarang();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbahActionPerformed
        // TODO add your handling code here:
        int jumlah = Integer.parseInt(jTextFieldJMLBR.getText());
        int harga = Integer.parseInt(jTextFieldHargaBr.getText());
        int hargaj = Integer.parseInt(jTextFieldHargaJs.getText());
        int total = (harga*jumlah) + hargaj;
        Date p = jDateChooser1.getDate();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalLahirStr = dateFormat.format(p);
        
        try {
            String sql1 = "UPDATE penjualan set id_barang='" + jTextFieldIDBR.getText() + "', id_jasa='" + jTextFieldIDJasa.getText() + "', id_pelanggan='" + jTextFieldIDPel.getText() + "', jumlah=" + jumlah + ", total_harga=" + total + " WHERE id_penjualan ='" + jTextFieldIDPJ.getText() + "'";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql1);
            pstm.setString(1, jTextFieldIDPJ.getText());
            pstm.setString(2, jTextFieldIDPel.getText());
            pstm.setString(3, jTextFieldIDBR.getText());
            pstm.setString(4, jTextFieldIDJasa.getText());
            pstm.setInt(5, jumlah);
            pstm.setInt(6, total);
            pstm.setDate(7, java.sql.Date.valueOf(tanggalLahirStr));

            pstm.executeUpdate();
            tabelPenjualan();
            tabelBarang();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonUbahActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        
        String id = jTable1.getValueAt(baris, 0).toString();
        jTextFieldIDPJ.setText(id);
        
        String pel = jTable1.getValueAt(baris, 1).toString();
        jTextFieldIDPel.setText(pel);

        String barang = jTable1.getValueAt(baris, 2).toString();
        jTextFieldIDBR.setText(barang);

        String jasa = jTable1.getValueAt(baris, 3).toString();
        jTextFieldIDJasa.setText(jasa);

        String jumlah = jTable1.getValueAt(baris, 4).toString();
        jTextFieldJMLBR.setText(jumlah);
        
        String harga = jTable1.getValueAt(baris, 5).toString();
        jTextFieldHarga.setText(harga);
        
        Date pinjam = (Date) jTable1.getValueAt(baris, 6);
        jDateChooser1.setDate(pinjam);
    }//GEN-LAST:event_jTable1MouseClicked

//    public void id_auto() throws SQLException{
//        try{
//            Connection conn = koneksi.configDB();
//            Statement stat = conn.createStatement();
//            String sql = "SELECT max(right(id_penjualan,4)) from penjualan";
//            ResultSet rs = stat.executeQuery(sql);
//            while(rs.next()){
//                if(rs.next() == false){
//                    jTextFieldIDPJ.setText("PJ0001");
//                } else{
//                    rs.last();
//                    int set_id = rs.getInt(1) + 1;
//                    String no = String.valueOf(set_id);
//                    int id_next = no.length();
//                    for(int i = 0; i < 4 - id_next; i++){
//                        no = "0" + no;
//                    }
//                    jTextFieldIDPJ.setText("PJ" + no);
//                }
//            }
//        } catch(SQLException e){
//            
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel datadbarang;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JButton jButtonUbah;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableBarang;
    private javax.swing.JTable jTableJasa;
    private javax.swing.JTable jTablePelanggan;
    private javax.swing.JTextField jTextFieldCariBarang;
    private javax.swing.JTextField jTextFieldCariJasa;
    private javax.swing.JTextField jTextFieldCariPel;
    private javax.swing.JTextField jTextFieldCariPenjualan;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldHargaBr;
    private javax.swing.JTextField jTextFieldHargaJs;
    private javax.swing.JTextField jTextFieldIDBR;
    private javax.swing.JTextField jTextFieldIDJasa;
    private javax.swing.JTextField jTextFieldIDPJ;
    private javax.swing.JTextField jTextFieldIDPel;
    private javax.swing.JTextField jTextFieldJMLBR;
    private javax.swing.JPanel panelDbarang;
    // End of variables declaration//GEN-END:variables
}
