/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bdl;

import koneksi.koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AINA NUR ILLAH
 */
public class Form_Penjualan extends javax.swing.JPanel {

    protected void tabelBarang() {
        DefaultTableModel modelBrg = new DefaultTableModel();
        modelBrg.addColumn("ID BARANG");
        modelBrg.addColumn("NAMA BARANG");
        modelBrg.addColumn("JUMLAH");
        modelBrg.addColumn("HARGA");

        try {
            String sql1 = "SELECT * FROM barang ORDER BY id_barang";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql1);

            while (res.next()) {
                modelBrg.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4)});
            }
            jTableBarang.setModel(modelBrg);

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    protected void tabelJasa() {
        DefaultTableModel modelJasa = new DefaultTableModel();
        modelJasa.addColumn("ID JASA");
        modelJasa.addColumn("NAMA JASA");
        modelJasa.addColumn("HARGA");

        try {
            String sql1 = "SELECT * FROM jasa ORDER BY id_jasa";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql1);

            while (res.next()) {
                modelJasa.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3)});
            }
            jTableJasa.setModel(modelJasa);

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    protected void tabelPelanggan() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID PELANGGAN");
        model.addColumn("NAMA PELANGGAN");
        model.addColumn("NOMOR");
        model.addColumn("EMAIL");
        model.addColumn("ALAMAT");

        try {
            String sql = "SELECT * FROM pelanggan ORDER BY id_pelanggan";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
            }
            jTablePelanggan.setModel(model);

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    /**
     * Creates new form Form_Dbarang
     */
    public Form_Penjualan() {
        initComponents();
        tabelBarang();
        tabelJasa();
        tabelPelanggan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDbarang = new javax.swing.JPanel();
        datadbarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableJasa = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableBarang = new javax.swing.JTable();
        jTextFieldIDPJ = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIDBR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldJMLBR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIDJasa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIDPel = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePelanggan = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        panelDbarang.setLayout(new java.awt.CardLayout());

        datadbarang.setBackground(new java.awt.Color(204, 204, 255));
        datadbarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setText("Penjualan");
        datadbarang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 19, -1, -1));

        jTableJasa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Jasa", "Nama Jasa", "Harga Jasa"
            }
        ));
        jTableJasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableJasaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableJasa);

        datadbarang.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 476, 250));

        jTableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Barang", "Nama Barang", "Jumlah Barang Supply", "Harga"
            }
        ));
        jTableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBarangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableBarang);

        datadbarang.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 96, 470, 250));
        datadbarang.add(jTextFieldIDPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 112, 150, -1));

        jLabel2.setText("ID Penjualan");
        datadbarang.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 85, -1, -1));

        jLabel3.setText("ID Barang");
        datadbarang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 165, -1, -1));
        datadbarang.add(jTextFieldIDBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 192, 150, -1));

        jLabel4.setText("Jumlah Barang");
        datadbarang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 247, -1, -1));
        datadbarang.add(jTextFieldJMLBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 274, 150, -1));

        jLabel5.setText("ID Jasa");
        datadbarang.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 85, -1, -1));
        datadbarang.add(jTextFieldIDJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 112, 155, -1));

        jLabel6.setText("ID Pelanggan");
        datadbarang.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 165, -1, -1));
        datadbarang.add(jTextFieldIDPel, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 192, 155, -1));

        jTablePelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Pelanggan", "Nama Pelanggan", "Nomor Telpon", "Email", "Alamat"
            }
        ));
        jTablePelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePelangganMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTablePelanggan);

        datadbarang.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 420, 250));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Pelanggan");
        datadbarang.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 364, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Jasa");
        datadbarang.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 364, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Barang");
        datadbarang.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 50, -1, -1));

        jButton1.setText("jButton1");
        datadbarang.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, 40));

        panelDbarang.add(datadbarang, "card2");

        add(panelDbarang, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jTableJasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableJasaMouseClicked
        // TODO add your handling code here:
        int baris = jTableJasa.rowAtPoint(evt.getPoint());

        String id = jTablePelanggan.getValueAt(baris, 0).toString();
        jTextFieldIDJasa.setText(id);
    }//GEN-LAST:event_jTableJasaMouseClicked

    private void jTablePelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePelangganMouseClicked
        // TODO add your handling code here:
        int baris = jTablePelanggan.rowAtPoint(evt.getPoint());

        String id = jTablePelanggan.getValueAt(baris, 0).toString();
        jTextFieldIDPel.setText(id);
    }//GEN-LAST:event_jTablePelangganMouseClicked

    private void jTableBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBarangMouseClicked
        // TODO add your handling code here:
        int baris = jTableBarang.rowAtPoint(evt.getPoint());

        String id = jTablePelanggan.getValueAt(baris, 0).toString();
        jTextFieldIDBR.setText(id);
    }//GEN-LAST:event_jTableBarangMouseClicked
  

//    public void id_auto() throws SQLException{
//        try{
//            Connection conn = koneksi.configDB();
//            Statement stat = conn.createStatement();
//            String sql = "SELECT max(right(id_penjualan,4)) from penjualan";
//            ResultSet rs = stat.executeQuery(sql);
//            while(rs.next()){
//                if(rs.next() == false){
//                    jTextFieldIDPJ.setText("PJ0001");
//                } else{
//                    rs.last();
//                    int set_id = rs.getInt(1) + 1;
//                    String no = String.valueOf(set_id);
//                    int id_next = no.length();
//                    for(int i = 0; i < 4 - id_next; i++){
//                        no = "0" + no;
//                    }
//                    jTextFieldIDPJ.setText("PJ" + no);
//                }
//            }
//        } catch(SQLException e){
//            
//        }
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel datadbarang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableBarang;
    private javax.swing.JTable jTableJasa;
    private javax.swing.JTable jTablePelanggan;
    private javax.swing.JTextField jTextFieldIDBR;
    private javax.swing.JTextField jTextFieldIDJasa;
    private javax.swing.JTextField jTextFieldIDPJ;
    private javax.swing.JTextField jTextFieldIDPel;
    private javax.swing.JTextField jTextFieldJMLBR;
    private javax.swing.JPanel panelDbarang;
    // End of variables declaration//GEN-END:variables
}
