/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bdl;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import koneksi.koneksi;

/**
 *
 * @author AINA NUR ILLAH
 */
public class Form_Penjualan extends javax.swing.JPanel {

    /**
     * Creates new form Form_Dbarang
     */
    public Form_Penjualan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDbarang = new javax.swing.JPanel();
        datadbarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextFieldIDPJ = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIDBR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldJMLBR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIDJasa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIDPel = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        panelDbarang.setLayout(new java.awt.CardLayout());

        datadbarang.setBackground(new java.awt.Color(204, 204, 255));
        datadbarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setText("Penjualan");
        datadbarang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 19, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        datadbarang.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 364, 421, 250));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        datadbarang.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 364, 476, 250));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        datadbarang.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 96, 326, 250));
        datadbarang.add(jTextFieldIDPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 112, 150, -1));

        jLabel2.setText("ID Penjualan");
        datadbarang.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 85, -1, -1));

        jLabel3.setText("ID Barang");
        datadbarang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 165, -1, -1));
        datadbarang.add(jTextFieldIDBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 192, 150, -1));

        jLabel4.setText("Jumlah Barang");
        datadbarang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 247, -1, -1));
        datadbarang.add(jTextFieldJMLBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 274, 150, -1));

        jLabel5.setText("ID Jasa");
        datadbarang.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 85, -1, -1));
        datadbarang.add(jTextFieldIDJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 112, 155, -1));

        jLabel6.setText("ID Pelanggan");
        datadbarang.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 165, -1, -1));
        datadbarang.add(jTextFieldIDPel, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 192, 155, -1));

        panelDbarang.add(datadbarang, "card2");

        add(panelDbarang, "card2");
    }// </editor-fold>//GEN-END:initComponents


    public void id_auto() throws SQLException{
        try{
            Connection conn = koneksi.configDB();
            Statement stat = conn.createStatement();
            String sql = "SELECT max(right(id_penjualan,4)) from penjualan";
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                if(rs.next() == false){
                    jTextFieldIDPJ.setText("PJ0001");
                } else{
                    rs.last();
                    int set_id = rs.getInt(1) + 1;
                    String no = String.valueOf(set_id);
                    int id_next = no.length();
                    for(int i = 0; i < 4 - id_next; i++){
                        no = "0" + no;
                    }
                    jTextFieldIDPJ.setText("PJ" + no);
                }
            }
        } catch(SQLException e){
            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel datadbarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextFieldIDBR;
    private javax.swing.JTextField jTextFieldIDJasa;
    private javax.swing.JTextField jTextFieldIDPJ;
    private javax.swing.JTextField jTextFieldIDPel;
    private javax.swing.JTextField jTextFieldJMLBR;
    private javax.swing.JPanel panelDbarang;
    // End of variables declaration//GEN-END:variables
}
