/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bdl;

import koneksi.koneksi;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AINA NUR ILLAH
 */
public class Form_Pelanggan extends javax.swing.JPanel {

    protected void masukTabel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID PELANGGAN");
        model.addColumn("NAMA PELANGGAN");
        model.addColumn("NOMOR");
        model.addColumn("EMAIL");
        model.addColumn("ALAMAT");

        try {
            String sql = "SELECT * FROM pelanggan ORDER BY id_pelanggan";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
            }
            jTable1.setModel(model);

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    protected void clear() {
        jTextFieldID.setText(null);
        jTextFieldNama.setText(null);
        jTextFieldNomor.setText(null);
        jTextFieldEmail.setText(null);
        jTextFieldAlamat.setText(null);

    }

    /**
     * Creates new form Form_Barang
     */
    public Form_Pelanggan() {
        initComponents();
        masukTabel();
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataBarang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonHapus = new javax.swing.JButton();
        bt_tambah = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldNomor = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonEdit = new javax.swing.JButton();
        jTextFieldCari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextFieldAlamat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tambahBarang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonSimpan = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButtonSimpan1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(204, 255, 204));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataBarang.setBackground(new java.awt.Color(204, 204, 255));
        dataBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Pelanggan", "Nama Pelanggan", "Nomor Telpon", "Email", "Alamat"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        dataBarang.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 245, 790, 300));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setText("Data Pelanggan");
        dataBarang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 19, -1, -1));

        jButtonHapus.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jButtonHapus.setText("HAPUS");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        dataBarang.add(jButtonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 40));

        bt_tambah.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        bt_tambah.setText("TAMBAH");
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });
        dataBarang.add(bt_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 40));

        jButtonBatal.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jButtonBatal.setText("BATAL");
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });
        dataBarang.add(jButtonBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 100, 40));
        dataBarang.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 198, 130, -1));
        dataBarang.add(jTextFieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 198, 130, -1));
        dataBarang.add(jTextFieldNomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 198, 130, -1));
        dataBarang.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 198, 130, -1));

        jLabel7.setText("ID Pelanggan");
        dataBarang.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel8.setText("Nama Pelanggan");
        dataBarang.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabel9.setText("Nomor");
        dataBarang.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jLabel10.setText("Email");
        dataBarang.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        jButtonEdit.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jButtonEdit.setText("EDIT");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        dataBarang.add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 100, 40));

        jTextFieldCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCariKeyReleased(evt);
            }
        });
        dataBarang.add(jTextFieldCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 120, 30));

        jLabel11.setText("Cari");
        dataBarang.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nama", "Nomor", "Email", "Alamat" }));
        dataBarang.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));
        dataBarang.add(jTextFieldAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 130, -1));

        jLabel12.setText("Alamat");
        dataBarang.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, -1));

        mainPanel.add(dataBarang, "card2");

        tambahBarang.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setText("Tambah Data Barang");

        jButtonSimpan.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jButtonSimpan.setText("SIMPAN");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        bt_batal.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        bt_batal.setText("BATAL");
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setText("Id Barang ");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setText("Nama Barang");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setText("Harga ");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setText("Jumlah Barang Supply");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 611, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jButtonSimpan1.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jButtonSimpan1.setText("UBAH");

        javax.swing.GroupLayout tambahBarangLayout = new javax.swing.GroupLayout(tambahBarang);
        tambahBarang.setLayout(tambahBarangLayout);
        tambahBarangLayout.setHorizontalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tambahBarangLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(tambahBarangLayout.createSequentialGroup()
                        .addComponent(jButtonSimpan)
                        .addGap(25, 25, 25)
                        .addComponent(jButtonSimpan1)
                        .addGap(25, 25, 25)
                        .addComponent(bt_batal))))
        );
        tambahBarangLayout.setVerticalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(tambahBarang, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM pelanggan WHERE id_pelanggan = '" + jTextFieldID.getText() + "'";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        masukTabel();
        clear();
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO pelanggan VALUES (?, ?, ?, ?, ?)";
            Connection konn = (Connection) koneksi.configDB();
            PreparedStatement stat = konn.prepareStatement(sql);
            stat.setString(1, jTextFieldID.getText());
            stat.setString(2, jTextFieldNama.getText());
            stat.setString(3, jTextFieldNomor.getText());
            stat.setString(4, jTextFieldEmail.getText());
            stat.setString(5, jTextFieldAlamat.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
            clear();
            jTextFieldID.requestFocus();
            masukTabel();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE pelanggan SET nama_pelanggan='" + jTextFieldNama.getText() + "', no_telp_pelanggan='" + jTextFieldNama.getText() + "', email_pelanggan='" + jTextFieldEmail.getText() + "', alamat_pelanggan='" + jTextFieldAlamat.getText() + "' WHERE id_pelanggan='" + jTextFieldID.getText() + "'";
//            String sql = "UPDATE barang SET nama_barang='" + jTextFieldNama.getText() + "', jumlah_br_sup= jumlah_br_sup - " + jml + ", harga=" + hrg + " WHERE id_barang='" + jTextFieldID.getText() + "'";

            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil diedit!");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        masukTabel();
        clear();
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());

        String id = jTable1.getValueAt(baris, 0).toString();
        jTextFieldID.setText(id);

        String nama = jTable1.getValueAt(baris, 1).toString();
        jTextFieldNama.setText(nama);

        String no_telp = jTable1.getValueAt(baris, 2).toString();
        jTextFieldNomor.setText(no_telp);

        String email = jTable1.getValueAt(baris, 3).toString();
        jTextFieldEmail.setText(email);
        
        String alamat = jTable1.getValueAt(baris, 4).toString();
        jTextFieldAlamat.setText(alamat);
    }//GEN-LAST:event_jTable1MouseClicked

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(dataBarang);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bt_batalActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        //        String jumlah = jTextField3.getText();
        //        String harga = jTextField4.getText();
        //
        //        int jml = Integer.parseInt(jumlah);
        //        int hrg = Integer.parseInt(harga);
        //        try {
        //            String sql = "INSERT INTO barang VALUES (?, ?, ?, ?)";
        //            Connection konn = (Connection) koneksi.configDB();
        //            PreparedStatement stat = konn.prepareStatement(sql);
        //            stat.setString(1, jTextField1.getText());
        //            stat.setString(2, jTextField2.getText());
        //            stat.setInt(3, jml);
        //            stat.setInt(4, hrg);
        //
        //            stat.executeUpdate();
        //            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
        //            clear();
        //            jTextField1.requestFocus();
        //            masukTabel();
        //        } catch (HeadlessException | SQLException e) {
        //            JOptionPane.showMessageDialog(this, e.getMessage());
        //        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jTextFieldCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCariKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        try {
            Connection conn = (Connection) koneksi.configDB();

            if (jComboBox1.getSelectedIndex() == 0) {
                String sql = "SELECT * FROM pelanggan WHERE id_pelanggan LIKE '%" + jTextFieldCari.getText() + "%'";
                PreparedStatement stat = conn.prepareStatement(sql);
                ResultSet res = stat.executeQuery();
                while (res.next()) {
                    model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
                }
            } else if (jComboBox1.getSelectedIndex() == 1) {
                String sql = "SELECT * FROM pelanggan WHERE nama_pelanggan ILIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'";
                PreparedStatement stat = conn.prepareStatement(sql);
                ResultSet res = stat.executeQuery();
                while (res.next()) {
                    model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
                }
            } else if (jComboBox1.getSelectedIndex() == 2) {
                String sql = "SELECT * FROM pelanggan WHERE no_telp_pelanggan LIKE '%" + jTextFieldCari.getText() + "%'";
                PreparedStatement stat = conn.prepareStatement(sql);
                ResultSet res = stat.executeQuery();
                while (res.next()) {
                    model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
                }
            } else if (jComboBox1.getSelectedIndex() == 3) {
                String sql = "SELECT * FROM pelanggan WHERE email_pelanggan ILIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'";
                PreparedStatement stat = conn.prepareStatement(sql);
                ResultSet res = stat.executeQuery();
                while (res.next()) {
                    model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
                }
            } else if (jComboBox1.getSelectedIndex() == 4){
                String sql = "SELECT * FROM pelanggan WHERE alamat_pelanggan ILIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'";
                PreparedStatement stat = conn.prepareStatement(sql);
                ResultSet res = stat.executeQuery();
                while (res.next()) {
                    model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
                }
            }
            jTable1.setModel(model);
        } catch (SQLException e) {

        }
    }//GEN-LAST:event_jTextFieldCariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JPanel dataBarang;
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonSimpan1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNomor;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel tambahBarang;
    // End of variables declaration//GEN-END:variables
}
